[theme]
base = "dark"
primaryColor = "#37e6ff"
backgroundColor = "#04070d"
secondaryBackgroundColor = "#091420"
textColor = "#d7f7ff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
